spring:
  application:
    name: spring-practice
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB