spring:
  application:
    name: spring-practice
  mvc:
    problemdetails:
      enabled: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/my_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mongodb:
    uri: mongodb://admin:admin@localhost:27017/my_database?authSource=admin
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}{faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%msg){green}%n"
